version: '3.8'

services:
  pomodoro-app:
    container_name: pomodoro-prod
    image: pomodoro-lts:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped